 
preload = /home/lbn/wallpaper/1.jpg
preload = /home/lbn/wallpaper/2.jpg
wallpaper {
    monitor = HDMI-A-1
    path = /home/lbn/wallpaper/1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/lbn/wallpaper/2.jpg
    fit_mode = cover
}

splash = false
